---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Mail
  - Facetime
  - Contacts
  - Reminders
  - Notes
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages

dockitems_persist:
  - name: "Things"
    path: "/Applications/Things.app/"
    pos: 1
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
    pos: 2
  - name: "Drafts"
    path: "/Applications/Drafts.app/"
    pos: 3
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 4
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 5
  - name: "Airtable"
    path: "/Applications/Airtable.app/"
    pos: 6
  - name: "Ulysses"
    path: "/Applications/Ulysses.app/"
    pos: 7
  - name: "Spark"
    path: "/Applications/Spark.app/"
    pos: 8
  - name: "Bear"
    path: "/Applications/Bear.app/"
    pos: 9
  - name: "Music"
    path: "/Applications/Music.app/"
    pos: 10
  - name: "App Store"
    path: "/Applications/App Store.app/"
    pos: 11
  - name: "Maps"
    path: "/Applications/Maps.app/"
    pos: 12
  - name: "Maps"
    path: "/Applications/Maps.app/"
    pos: 12
  - name: "Photos"
    path: "/Applications/Photos.app/"
    pos: 13
  - name: "System Preferences"
    path: "/Applications/System Preferences.app/"
    pos: 14

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_us_brewfile: false
homebrew_installed_packages:
  - git
  - github/gh/gh
  - go
  - sqlite
  - node
  - nvm

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - slack
  - transmit
  - alfred
  - tower

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: ghost-cli
    state: present
  - name: gscan
    state: present
  - name: gulp
    state: present

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
